
[build]
  functions = "netlify/functions"
  publish = "/"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Run function when a Netlify Forms submission is created
[[events]]
  event = "submission_created"
  command = "node netlify/functions/form-to-gcal.js"
